DROP TABLE IF EXISTS albums, reviews, users CASCADE;

CREATE TABLE albums (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  join_date DATE DEFAULT CURRENT_DATE NOT NULL,
  password VARCHAR(20) NOT NULL
);

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY,
  album INTEGER REFERENCES albums(id) NOT NULL,
  author INTEGER REFERENCES users(id) NOT NULL,
  review VARCHAR(150) NOT NULL,
  submission_date DATE DEFAULT CURRENT_DATE NOT NULL
);
